### ISSUE TITLE
Enable `global-hub.open-cluster-management.io/with-inventory: ` doesn't set the ACL for the `kessel-inventory` topic

### ISSUE THREAD

**Issue by akoserwal** [stolostron/multicluster-global-hub#1103]
```kind: MulticlusterGlobalHub
metadata:
  Annotations:
    global-hub.open-cluster-management.io/with-inventory: ''
```
Kafka user CR create for global hub user
```
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: gh-spec
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Describe
          - Read
        resource:
          name: gh-status.
          patternType: prefix
          type: topic
    type: simple
```
https://github.com/stolostron/multicluster-global-hub/blob/f873a048eda1af956137b562ab20c0671fb22c59/operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-user.yaml#L35

I don't see the permissions got created
 {{ if .EnableInventoryAPI }}
    - host: '*'
      operations:
      - Describe
      - Read
      - Write
      resource:
        name: {{.KafkaInventoryTopic}}
        patternType: literal
        type: topic
{{ end }}
